---
- name: Install and configure nginx
  hosts: webservers
  become: true
  vars:
    nginx_listen_port: 4881

  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Create nginx config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
